### ISSUE TITLE
Supressão de erros de insert ou update

### ISSUE THREAD

**Issue by sergiosilva-nsj** [Nasajon/nsj_gcf_utils#2]
https://github.com/Nasajon/nsj_gcf_utils/blob/00946ecdbe8c18356d6ca5fd80dea6a6d41ff7b9/src/nsj_gcf_utils/db_adapter2.py#L47

Acredito que essa linha pode suprimir erros... Ou temos que trocar para um except específico, ou fazer algo como:
```python
            if 'returning' in sql.lower():
                rs = cur.fetchall()
                returning = [dict(rec.items()) for rec in rs]
            else:
                returning = None
```

Tirando o try except daqui

**Comment by carlosbenevides** [comment]
Fiz o ajuste com o código que vc colocou no comentário
